# This is a basic workflow to help you get started with Actions

name: Post to docs website

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main

      # Create/update llms-full.txt with contents of all .md files in docs/books
      - name: Generate llms-full.txt
        run: |
          find docs/books -name "*.md" -print0 | xargs -0 cat | iconv -f ASCII -t UTF-8//IGNORE | awk '{print} END {print "\n\n"}' > docs/llms-full.txt || echo "Failed to generate llms-full.txt"

      - name: Install upx CLI
        run: |
          wget https://github.com/upyun/upx/releases/download/v0.3.5/upx_0.3.5_linux_x86_64.tar.gz
          sudo tar -zxvf upx_0.3.5_linux_x86_64.tar.gz
          sudo cp upx /bin/

      - name: Login UPYUN
        run: sudo ./upx login docs-zblogcn-all ${{secrets.UPYUN_OPERATOR}} ${{secrets.UPYUN_PASSWORD}}

      # - name: Delete files
      #   run: sudo ./upx rm /php -d

      - name: Sync files
        run: sudo ./upx sync $GITHUB_WORKSPACE/docs /php
